#  Copyright (c) 2020, 2021, Oracle and/or its affiliates.
#
#  This software is dual-licensed to you under the Universal Permissive License
#  (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License
#  2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
#  either license.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# This script will start an Oracle Database inside a Docker container and then
# execute the Oracle R2DBC test suite with a configuration that has it connect
# to that database.
#
# This script makes no attempt to clean up. The docker container is left
# running, and the database retains the test user and any other modifications
# that the test suite may have performed.
# It is assumed that the Github Runner will clean up any state this script
# leaves behind.

name: Build and Test Oracle R2DBC

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development

jobs:
  # Builds the Oracle R2DBC Driver using Maven
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
  # Tests the Oracle R2DBC Driver with an 18.4 XE Oracle Database
  test-18-4-xe:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Oracle Database 18.4.0 XE
        run: cd $GITHUB_WORKSPACE/.github/workflows && bash test.sh 18.4.0 50184
  # Tests the Oracle R2DBC Driver with a 21.3 XE Oracle Database
  test-21-3-xe:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Oracle Database 21.3.0 XE
        run: cd $GITHUB_WORKSPACE/.github/workflows && bash test.sh 21.3.0 50213
